In [ ]:
1+1

2

## DATA TYPES
1. NUMERIC
2. STRING
3. LIST
4. TUPLE
5. DICTIONARY
6. SETS

## NUMPY
for mathematical use and Array Based calculations

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
## Creating a 1D array
arra_1d = np.array([1,2,3,4,5,6])
print(type(arra_1d))
print(arra_1d)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [ ]:
arra_2d = np.array([[1,2,3],[4,5,6]])
arra_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
range = np.arange(10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sqrt = np.sqrt(range)
sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
arra_1d.max()

6

## Pandas

In [ ]:
s = pd.Series([1,2,3,4,5,6])


In [ ]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
## Create a DataFrame from Dictionary

data = {
    "A": [1,2,3,5],
    "B": [4,5,6,7],
    "C": [7,8,9,10]
}


In [ ]:
df = pd.DataFrame(data)
print(df)
print(type(df))

   A  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  5  7  10
<class 'pandas.core.frame.DataFrame'>


In [ ]:
df = pd.DataFrame(data, index=["Row1","Row2","Row3","Row4"])
df

A  B   C
Row1  1  4   7
Row2  2  5   8
Row3  3  6   9
Row4  5  7  10

## Matplotlib & Seaborn

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns